# Generated by Django 2.2.16 on 2022-11-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(related_name='titles', to='reviews.Genre'),
        ),
    ]
